export const RESOURCES = {
  CHANGE_AMOUNT: 'CHANGE_RESOURCE_AMOUNT',
}

export const SYSTEMS = {
  ELECTRIC: {
    ON: 'ELECTRIC_SYSTEM_ON',
    OFF: 'ELECTRIC_SYSTEM_OFF',
    TICK: 'ELECTRIC_TICK',
    OVERCHARGE: 'ELECTRIC_OVERCHARGE',
    ADD_CHARGE: 'ELECTRIC_ADD_CHARGE',
    TOGGLE_STORING: 'ELECTRIC_TOGGLE_STORING',
  },
  WATER: {
    ON: 'WATER_SYSTEM_ON',
    OFF: 'WATER_SYSTEM_OFF',
    TICK: 'WATER_TICK',
    CHANGE_FLOW_DIRECTION: 'CHANGE_FLOW_DIRECTION',
  },
}

export const COMPLEX = {
  TRANSFER_CHARGE: 'TRANSFER_CHARGE',
}
